SYSTEM:
  NUM_GPUS: 2
  NUM_WORKERS: 8
  AMP_OPT_LEVEL: 'O0'
  OUTPUT: ''
  TAG: ''
  SAVE_FREQ: 1
  PRINT_FREQ: 1
  SEED: 0
  EVAL_MODE: False
  LOCAL_RANK: 0
DATA:
  BATCH_SIZE: 8
  DATA_PATH: './dataset/CCD_real/'
  DATASET: 'CCD'
  IMG_SIZE: 256
  PIN_MEMORY: False
MODEL:
  RESUME:  #if not use, empty
  NUM_CLASSES: 2
  DROP_RATE: 0.0 #defult is 0
  DROP_PATH_RATE: 0.2
  SWIN:
    PATCH_SIZE: 4
    IN_CHANS: 6
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 8
    MLP_RATIO: 4.
    QKV_BIAS: True
    QK_SCALE: #None
    APE: False
    PATCH_NORM: True
TRAIN:
  START_EPOCH: 0
  WARMUP_EPOCHS: 20
  EPOCHS: 300
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.0e-3 #5.0e-4
  MIN_LR: 1.0e-5 #5.0e-6
  CLIP_GRAD: 5.0
  AUTO_RESUME: True #NOT USED see   RESUME:
  ACCUMULATION_STEPS: 2
  USE_CHECKPOINT: False #NOT USED see   RESUME:
  LOSS_WEIGHT: [0.2,0.8]
  LR_SCHEDULER: 
    NAME: 'cosine'
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1
  OPTIMIZER:
    NAME: 'adamw'
    EPS: 1.0E-8
    BETAS: (0.9,0.999,) #tuple
    MOMENTUM: 0.9
AUG: True
TEST:
  EVAL: False #NOT USED
  

